import { useState } from 'react'
import './dashboard.css'
import './layout-fixes.css'
import './ui-change-overrides.css'

type User = { email: string; password: string; name: string; role: string }
const users: User[] = [
  { email: 'teacher@edspec.demo', password: 'Teacher@123', name: 'Demo Teacher', role: 'Teacher' },
  { email: 'reviewer@edspec.demo', password: 'Reviewer@123', name: 'Demo Reviewer', role: 'Reviewer' },
  { email: 'student@edspec.demo', password: 'Student@123', name: 'Demo Student', role: 'Student' },
  { email: 'admin@edspec.demo', password: 'Admin@123', name: 'Demo Admin', role: 'Admin' },
]
// Demo-only POC credentials. There is no real authentication in this prototype.
type Spec = { id: string; version: string; status: string; title: string; subject: string; learningObjective: string; questionRules: { totalQuestions: number; questionType: string; optionsPerQuestion: number }; difficultyDistribution: { easy: number; medium: number; hard: number }; scoringRules: { pointsPerQuestion: number; totalPoints: number }; approval: { required: boolean; approvedBy: string | null; approvedAt: string | null }; createdAt: string; updatedAt: string }
type Question = { id: string; learningObjective: string; difficulty: string; questionType: string; prompt: string; options: { id: string; text: string }[]; correctOptionId: string; points: number }
type Assessment = { id: string; specificationId: string; specificationVersion: string; status: string; questions: Question[]; createdBy: string; createdAt: string }
type Form = { id: string; version: string; title: string; subject: string; learningObjective: string; totalQuestions: number; questionType: string; optionsPerQuestion: number; easy: number; medium: number; hard: number; pointsPerQuestion: number; totalPoints: number }
const blank: Form = { id: 'algebra-basic-001', version: '1.0.0', title: 'Basic Algebra', subject: 'Mathematics', learningObjective: 'Solve single-variable linear equations', totalQuestions: 5, questionType: 'multiple-choice', optionsPerQuestion: 4, easy: 2, medium: 2, hard: 1, pointsPerQuestion: 2, totalPoints: 10 }
const specificationVersions = [
  { id: 'algebra-basic', version: '1.0.0', title: 'Basic Algebra Assessment', subject: 'Basic Algebra', status: 'approved', updated: 'Aug 17, 2026' },
  { id: 'algebra-basic-001', version: '1.0.0', title: 'Basic Algebra', subject: 'Mathematics', status: 'approved', updated: 'Aug 14, 2026' },
  { id: 'algebra-basic-001', version: '2.0.0', title: 'Basic Algebra', subject: 'Mathematics', status: 'approved', updated: 'Aug 14, 2026' },
  { id: 'algebra-basic-001', version: '5.0.1', title: 'Basic Algebra', subject: 'Mathematics', status: 'approved', updated: 'Aug 17, 2026' },
  { id: 'science-basic-001', version: '4.0.0', title: 'Basic Science', subject: 'Science', status: 'draft', updated: 'Aug 14, 2026' },
  { id: 'science-basic-001', version: '4.0.1', title: 'Basic Science', subject: 'Science', status: 'approved', updated: 'Aug 14, 2026' },
]
async function api<T>(path: string, init?: RequestInit): Promise<T> { const r = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...init }); const body = await r.json().catch(() => ({})); if (!r.ok) { const errors = body.errors ? Object.values(body.errors).flat().join(' ') : body.message; throw new Error(errors || `${r.status} request failed`) } return body as T }
function App() { const [user, setUser] = useState<User | null>(() => JSON.parse(sessionStorage.getItem('edspec-user') || 'null')); const [spec, setSpec] = useState<Spec | null>(null); const [assessment, setAssessment] = useState<Assessment | null>(null); const [view, setView] = useState<'overview' | 'create' | 'detail' | 'assessment'>('overview'); const [form, setForm] = useState<Form>(blank); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  if (!user) return <Login onLogin={u => { sessionStorage.setItem('edspec-user', JSON.stringify(u)); setUser(u) }} />
  const run = async (action: () => Promise<void>, success: string) => { setBusy(true); setError(''); setMessage(''); try { await action(); setMessage(success) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  const create = () => run(async () => { const s = await api<Spec>('/api/specifications/drafts', { method: 'POST', body: JSON.stringify(toCreate(form)) }); setSpec(s); fromSpec(s, setForm); setView('detail') }, 'Draft created successfully')
  const load = () => run(async () => { const s = await api<Spec>(`/api/specifications/${encodeURIComponent(form.id)}/versions/${encodeURIComponent(form.version)}`); setSpec(s); fromSpec(s, setForm); setView('detail') }, 'Specification loaded')
  const save = () => spec && run(async () => { const s = await api<Spec>(`/api/specifications/${spec.id}/versions/${spec.version}`, { method: 'PUT', body: JSON.stringify(toUpdate(form)) }); setSpec(s) }, 'Draft saved')
  const approve = () => spec && run(async () => { const s = await api<Spec>(`/api/specifications/${spec.id}/versions/${spec.version}/approve`, { method: 'POST', body: JSON.stringify({ approvedBy: user.name }) }); setSpec(s) }, 'Specification approved')
  const generate = () => spec && run(async () => { const result = await api<{ assessment: Assessment }>(`/api/specifications/${spec.id}/versions/${spec.version}/assessments/generate`, { method: 'POST', body: JSON.stringify({ requestedBy: user.name }) }); setAssessment(result.assessment); setView('assessment') }, 'Assessment generated')
  const logout = () => { sessionStorage.removeItem('edspec-user'); setUser(null) }
  return <div className="app"><aside><div className="brand"><b>EdSpec</b><small>AI · POC WORKSPACE</small></div><div className="workspace">WORKSPACE</div><nav><button className={view === 'overview' ? 'active' : ''} onClick={() => setView('overview')}>⌂　Overview</button><button className={view === 'create' || view === 'detail' ? 'active' : ''} onClick={() => setView('create')}>◇　Specifications <span>8</span></button><button className={view === 'assessment' ? 'active' : ''} onClick={() => setView('assessment')}>▤　Assessments</button><button onClick={() => setMessage('Review queue is not available in the current backend')}>◉　Review queue <span>2</span></button><button onClick={() => setMessage('Audit history is not available in the current backend')}>◷　Audit history</button></nav><div className="profile"><b>{user.name}</b><small>{user.role} · Demo identity</small><button className="link" onClick={logout}>Sign out</button></div></aside><main><header><span>REVIEWER WORKSPACE <i>/ {view}</i></span><strong>Backend authoritative</strong></header><section className="wrap">{message && <div className="success">✓ {message}</div>}{error && <div className="error"><b>Request failed</b><div>{error}</div></div>}{view === 'overview' && <Dashboard onCreate={() => setView('create')} onOpen={() => { setForm({ ...blank, version: '5.0.1' }); setView('detail') }} />}{view === 'create' && <Create form={form} setForm={setForm} onCreate={create} onLoad={load} busy={busy} />}{view === 'detail' && spec && <Detail spec={spec} form={form} setForm={setForm} onSave={save} onApprove={approve} onGenerate={generate} busy={busy} user={user} />}{view === 'assessment' && assessment && <AssessmentView assessment={assessment} />}{view === 'assessment' && !assessment && <Dashboard onCreate={() => setView('create')} onOpen={() => setView('create')} />}</section></main></div> }
function Dashboard({ onCreate, onOpen }: { onCreate: () => void; onOpen: () => void }) { return <><div className="dashboard-title"><div><small>REVIEWER WORKSPACE</small><h1>Good morning, Arti</h1><p>Here’s what needs your attention today.</p></div><button className="primary" onClick={onCreate}>＋ New specification</button></div><div className="stats"><div><span>◇</span><label>Approved specifications<b>8</b><small>↑ 1 this month</small></label></div><div><span>▤</span><label>Assessments generated<b>12</b><small>↑ 18% this month</small></label></div><div><span>◉</span><label>Awaiting review<b>2</b><small>Needs your attention</small></label></div></div><div className="dashboard-grid"><section className="card"><h2>Recent activity</h2><p className="muted">Your latest specification and assessment work.</p>{[['●','Specification approved','Basic Algebra · v5.0.1','Approved'],['●','Assessment generated','Basic Algebra · 5 questions','Generated'],['●','Draft specification','Basic Science · v4.0.0','Draft']].map(x => <div className="activity" key={x[1]}><i>{x[0]}</i><div><b>{x[1]}</b><small>{x[2]}</small></div><em>{x[3]}</em></div>)}</section><section className="card"><h2>Needs your attention</h2><p className="muted">Items waiting for a decision.</p><div className="queue"><b>!</b><div><strong>Basic Algebra assessment</strong><small>3 findings · 1 high severity</small></div><button className="secondary" onClick={onOpen}>Open</button></div><div className="queue"><b>◇</b><div><strong>Basic Science</strong><small>Draft specification</small></div><button className="secondary" onClick={onOpen}>Open</button></div></section></div></> }
function Login({ onLogin }: { onLogin: (u: User) => void }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); return <div className="login"><section className="login-card"><div className="logo">E</div><small>EDSPEC AI</small><h1>Welcome back</h1><p>Sign in with a demo identity to enter the POC workspace.</p><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <div className="error">{error}</div>}<button className="primary" onClick={() => { const u = users.find(x => x.email === email && x.password === password); u ? onLogin(u) : setError('Invalid demo email or password') }}>Sign in</button><div className="hint">Demo: teacher@edspec.demo / Teacher@123<br />Reviewer: reviewer@edspec.demo / Reviewer@123</div></section></div> }
function fields(f: Form, set: (f: Form) => void, disabled = false) { const update = (key: keyof Form, value: string) => set({ ...f, [key]: ['totalQuestions', 'optionsPerQuestion', 'easy', 'medium', 'hard', 'pointsPerQuestion', 'totalPoints'].includes(key) ? Number(value) : value }); return <div className="grid">{(['title', 'subject', 'learningObjective', 'questionType'] as const).map(key => <label key={key}>{key === 'learningObjective' ? 'Learning objective' : key[0].toUpperCase() + key.slice(1)}<input disabled={disabled} value={f[key]} onChange={e => update(key, e.target.value)} /></label>)}{(['totalQuestions', 'optionsPerQuestion', 'easy', 'medium', 'hard', 'pointsPerQuestion', 'totalPoints'] as const).map(key => <label key={key}>{key.replace(/[A-Z]/g, m => ` ${m}`).replace(/^./, m => m.toUpperCase())}<input disabled={disabled} type="number" value={f[key]} onChange={e => update(key, e.target.value)} /></label>)}</div> }
function Create({ form, setForm, onCreate, onLoad, busy }: { form: Form; setForm: (f: Form) => void; onCreate: () => void; onLoad: () => void; busy: boolean }) { const update = (key: keyof Form, value: string) => setForm({ ...form, [key]: key === 'id' || key === 'version' ? value : form[key] }); return <section className="card"><h2>Create a specification draft</h2><div className="grid"><label>ID (optional)<input value={form.id} onChange={e => update('id', e.target.value)} /></label><label>Version<input value={form.version} onChange={e => update('version', e.target.value)} /></label></div>{fields(form, setForm)}<div className="checks"><span className={form.easy + form.medium + form.hard === form.totalQuestions ? 'ok' : 'bad'}>Difficulty: {form.easy + form.medium + form.hard} / {form.totalQuestions}</span><span className={form.totalPoints === form.totalQuestions * form.pointsPerQuestion ? 'ok' : 'bad'}>Points: {form.totalPoints} / {form.totalQuestions * form.pointsPerQuestion}</span></div><div className="actions"><button className="secondary" onClick={onLoad} disabled={busy || !form.id}>Load ID/version</button><button className="primary" onClick={onCreate} disabled={busy}>{busy ? 'Working…' : 'Create draft'}</button></div></section> }
function Detail({ spec, form, setForm, onSave, onApprove, onGenerate, busy, user }: { spec: Spec; form: Form; setForm: (f: Form) => void; onSave: () => void; onApprove: () => void; onGenerate: () => void; busy: boolean; user: User }) { const edit = spec.status === 'draft'; return <section className="card"><div className="detail-head"><div><small>{spec.id} · v{spec.version}</small><h2>{spec.title}</h2></div><span className={`badge ${spec.status}`}>{spec.status}</span></div>{fields(form, setForm, !edit)}<dl><div><dt>Approved by</dt><dd>{spec.approval.approvedBy || 'Pending'}</dd></div><div><dt>Created</dt><dd>{new Date(spec.createdAt).toLocaleString()}</dd></div><div><dt>Updated</dt><dd>{new Date(spec.updatedAt).toLocaleString()}</dd></div></dl><div className="actions">{edit && <><button className="secondary" onClick={onSave} disabled={busy}>Save</button><button className="primary" onClick={onApprove} disabled={busy}>Approve as {user.name}</button></>}{!edit && <button className="primary" onClick={onGenerate} disabled={busy}>{busy ? 'Generating…' : 'Generate assessment'}</button>}</div></section> }
function AssessmentView({ assessment }: { assessment: Assessment }) { return <section><div className="card"><div className="detail-head"><div><small>{assessment.specificationId} · v{assessment.specificationVersion}</small><h2>Assessment output</h2></div><span className="badge generated">{assessment.status}</span></div><p>Created by {assessment.createdBy}. This result is held in React state for this session because no assessment GET endpoint exists.</p></div>{assessment.questions.map((q, i) => <article className="card question" key={q.id}><div className="question-title"><b>Question {i + 1}</b><span>{q.difficulty} · {q.points} points</span></div><h3>{q.prompt}</h3><p className="muted">{q.learningObjective} · {q.questionType}</p>{q.options.map(o => <div className={o.id === q.correctOptionId ? 'option correct' : 'option'} key={o.id}>{o.id}. {o.text}{o.id === q.correctOptionId && <b> ✓ Correct</b>}</div>)}</article>)}</section> }
function toCreate(f: Form) { return { id: f.id || undefined, version: f.version, title: f.title, subject: f.subject, learningObjective: f.learningObjective, questionRules: { totalQuestions: f.totalQuestions, questionType: f.questionType, optionsPerQuestion: f.optionsPerQuestion }, difficultyDistribution: { easy: f.easy, medium: f.medium, hard: f.hard }, scoringRules: { pointsPerQuestion: f.pointsPerQuestion, totalPoints: f.totalPoints } } }
function toUpdate(f: Form) { const { id: _id, version: _version, ...body } = toCreate(f); return body }
function fromSpec(s: Spec, set: (f: Form) => void) { set({ id: s.id, version: s.version, title: s.title, subject: s.subject, learningObjective: s.learningObjective, totalQuestions: s.questionRules.totalQuestions, questionType: s.questionRules.questionType, optionsPerQuestion: s.questionRules.optionsPerQuestion, easy: s.difficultyDistribution.easy, medium: s.difficultyDistribution.medium, hard: s.difficultyDistribution.hard, pointsPerQuestion: s.scoringRules.pointsPerQuestion, totalPoints: s.scoringRules.totalPoints }) }
export default App
